### PR TITLE
Fix typos/grammar in README

### PR DESCRIPTION
**Pull request by sbine**

### CODE REVIEW

**Comment by Lisennk** [comment]
Thanks for your changes! I will check it and merge in the next 5-6 hours. 

Also, I would be immensely grateful if you'd checked for mistakes and typos readme of my another package: https://github.com/Lisennk/Laravel-Slack-Web-API

Thanks once again. I promise, i will learn grammar soon (:

**Comment by Lisennk** [comment]
@sbine, look at first sentence:

> Work with Slack Events API as easily as native Laravel events and event listeners.

Maybe here is more correct to write

> Work with Slack Events API as easily as with native Laravel events and event listeners.

?

Anyway, merged it, thanks.

**Comment by sbine** [comment]
I think either way is readable, so if you like the second option better go for it! I'd be happy to take a look at your other repository this evening.

**Comment by Lisennk** [comment]
Thanks for help!

**Pull request merged**
