### PR TITLE
Event sent to Listener is empty.

### PR DESCRIPTION
**Pull request by pelmered**
Do not use new on event here, that creates a new empty event object and dispatches the empty object.
Please merge asap.

### CODE REVIEW

**Comment by pelmered** [comment]
Also, please release a new version so we don't have to use `dev-master` in Laravel 7. 

Besides this issue it seams to work fine in Laravel 7.

**Comment by bcosynot** [comment]
Hi, @Lisennk could you please merge this PR soon? Thank you!

**Comment by pelmered** [comment]
We have been running my fork(this PR) in production for almost two weeks now without any issues. 

@bcosynot If you just add this to your `composer.json` and run an update it should work until this is merged:

    "repositories": [
        [....]
        {
            "type": "vcs",
            "url": "https://github.com/pelmered/Slack-Events"
        }
    ],

**Comment by bcosynot** [comment]
Thanks @pelmered !

**Pull request merged**
